### ISSUE TITLE
Project name and trademark usage

### ISSUE THREAD

**Issue by dmbaturin** [ibehren1/fw-gui#20]
Hi Isaac,

It's cool to see people making automation tools for VyOS. However, the name "VyOS" is a registered trademark in the US (where you are located) and other countries, and we cannot allow its use without our permission, not least because we'll risk losing it and making it vulnerable to bad-faith actors if we do.

Just like if you made a tool for, say, RedHat Enterprise Linux, you could not name it "RedHat Enterprise Linux Firewall GUI" — that would misrepresent the tool as if it was produced or affiliated with RedHat, and any possible issues with it would harm the reputation of RedHat. Just like RedHat, we cannot allow that.

You should change the project name to make it clear that it's not affiliated with VyOS. If you don't, we can report it to GitHub for a repository takedown or take a legal action, but we hope that we can cooperate and it will not get to that.

P.S.

VyOS has HTTP APIs now that are far more reliable than SSH connections, you should consider using them.

**Comment by ibehren1** [comment]
Thank you for reaching out @dmbaturin .  I appreciate what you are saying and I was not looking infringe on the VyOS name or trademark.  I do want to make the tool findable for users of VyOS who would find it useful, but I fully respect and appreciate the great work that the developers of VyOS do and the product you are making available to the community.

What would you see as an appropriate name or way to reference VyOS?  Is there a document that describes the ways that the community can reference your brand?

Would the following be acceptable?
Firewall GUI for use with VyOS

I am curious what drew your attention today vs the last 6 weeks and my [posting](https://forum.vyos.io/t/vyos-firewall-configuration-gui-my-little-project/13391) about the work I was doing in the VyOS forum on 1/15/2024.  Did I do something or post something in a more egregious way?

Again, I appreciate what you are saying and want to make changes to fully alleviate your concern.  I want add to the ecosystem and not detract from it.

Thanks!

**Comment by dmbaturin** [comment]
There's nothing egregious, it was just in my backlog.

Regarding findability: I think it's ok to write something like "${name} is a firewall management tool for VyOS". We need to develop trademark guidelines for sure ­— it's a good reminder to work on them.

We should also add a website section for third-party tools and resources and your project would be a good fit for it.

**Comment by ibehren1** [comment]
Thanks for the reply @dmbaturin.  Given the changes made in #21, is it okay to close this issue?

**Comment by dmbaturin** [comment]
Yes, the branding looks good to me now, thanks!
