### ISSUE TITLE
Is subpath work?

### ISSUE THREAD

**Issue by zelogik** [ibehren1/fw-gui#33]
Hi,

is example.com/fw-gui/   is a valable working solutions ?

Have a k8s cluster and normally for many app just that 2 lines works:

annotations: nginx.ingress.kubernetes.io/rewrite-target: /$2
and
spec.rules...path: /fw-gui(/|$)(.*)

But there, I have a redirection to example.com/user_login?next=%2F, And not taking into account the /fw-gui/

Thanks

**Comment by ibehren1** [comment]
The published docker container is not setup for this -- I think you will have to make some changes to the app or put Nginx in front of the app.

This link addresses such hosting of a flash app.
https://stackoverflow.com/questions/67737069/how-to-host-a-flask-app-on-a-subfolder-url-prefix-with-nginx

Hope this helps.
