### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by xTITUSMAXIMUSX** [ibehren1/fw-gui#38]
I was building my own front end for vyos and came across your project. This looks really good and really helpful. I was taking a different aproach where I am using the pyvyos project to directly interact with the vyos API for 1.5. I was wondering if you wanted to help take a look and possibly help out the project?

https://github.com/xTITUSMAXIMUSX/vyerwall-gui

**Comment by ibehren1** [comment]
I appreciate the offer... I don't think I have the time at this point.

Certainly wish you luck!  I think it is great to have options in this area.
