### ISSUE TITLE
[Feature request] Will you implement Flowtable for forward chain?

### ISSUE THREAD

**Issue by MaurUppi** [ibehren1/fw-gui#44]
Hi there

This is my first time using the tool; it is a beautiful tool for the domain. 

However, the flowable should support zone-based firewall configuration. 
If I don't have a wrong understanding of this thread: https://vyos.dev/T4502#167277

If so, will you consider adding the flowable to this tool?

Thanks again.

**Comment by ibehren1** [comment]
@MaurUppi 

Thanks for the feedback and request.  I will consider adding visual support for Flowtables in the future.  They are not something that I am currently using and will need to do some research before implementing visually within the FW-GUI tool.

That said, the FW-GUI tool does currently support "Extra Configurations" where you are able to put configuration commands for any non-implemented items.

So as of today, you can do this by placing commands such as you sited in https://vyos.dev/T4502#167277 in your configuration as seen below.

Within your firewall configuration, on the right side click on the `Extra Configurations` button.
![image](https://github.com/user-attachments/assets/7df38296-2dac-4ee0-82a7-bde4da862c4c)

Then add your configurations in the text box as seen here and click `Add Configuration Items`.
![image](https://github.com/user-attachments/assets/3f7b9636-a5a7-4f64-bf5d-af3d96729836)

On the resulting screen which displays the configuration, you will see your extra configurations at the top.
![image](https://github.com/user-attachments/assets/07a176ba-7e6e-4074-9a39-b10dfba8ad62)

These configuration commands will then be pushed to your Vyos instance and maintained along with the rest of the configuration.

Hope this helps!

-----

For my own knowledge, will you share the following information with me?

Are you using FW-GUI today or just considering it?

How long have you been using FW-GUI?

How many VyOS firewall instances are you managing with FW-GUI?

Are these VyOS firewall instances used for business or personal?

What version of FW-GUI are you using?  Have you upgraded through multiple versions?

Have you deployed via Docker or manually from source?

What if any issues have you had while using FW-GUI?

**Comment by MaurUppi** [comment]
@ibehren1 

First and formost.  I'm newbie to manual configure Firewall settings. Thus, I'm looking for a tool help to impelment a basical with best practiced configuration for home use via PPPoE. 
That's why I'm trying and learning to use FW-GUI. 

Are you using FW-GUI today or just considering it?
- Like I said, learning manual of VyOS 1.4 firewall related seession and trying to build the config. Given I'm a newbie so I'm intent to use FW-GUI to aviod some config misstake. 

How long have you been using FW-GUI?
- No long, just few days. 

How many VyOS firewall instances are you managing with FW-GUI?
- Like I said, home network, just one VyOS based router. 

Are these VyOS firewall instances used for business or personal?
- Personal. 

What version of FW-GUI are you using? Have you upgraded through multiple versions?
- the latest one, set up by your docker-compose.yaml

Have you deployed via Docker or manually from source?
- Docker would be fine. 

What if any issues have you had while using FW-GUI?
- learning phase. but found that I can't delete preseted ssh_group or other config of your example config. Only able to add something. 
- reason of why is I'm assuming the example is a workable/typical configuration. Maybe I just modify/change base config like network group would be ready to implement. 


let me konw if you have more questions. 
thanks for your help.

**Comment by MaurUppi** [comment]
Meanwhile, would you mind helping me enhance or fine-tune the configuration below if you have time? 
Let me know if there is something i should have included but missed regarding home network circumstances. 
Thanks in advance. 

<details><summary>Details</summary>
<p>

```shell
#
# Global Configuration Items
#
set firewall global-options all-ping 'enable'
set firewall global-options broadcast-ping 'disable'
set firewall global-options ip-src-route 'disable'
set firewall global-options ipv6-src-route 'disable'
set firewall global-options log-martians 'enable'
set firewall global-options receive-redirects 'disable'
set firewall global-options send-redirects 'disable'
set firewall global-options source-validation 'strict'
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy invalid log
set firewall global-options state-policy invalid log-level 'warn'
set firewall global-options state-policy related action 'accept'
set firewall global-options syn-cookies 'enable'
set firewall global-options resolver-cache

#
# IPV4
#

# Group: Network, Interfaces, Ports
set firewall group network-group HomeLAN-v4 network '192.168.1.0/24'
set firewall group ipv6-network-group HomeLAN-v6 network 'fd12:3456:789a:1::/64'
set firewall group interface-group WAN interface eth2
set firewall group interface-group WAN interface pppoe0
set firewall group interface-group LAN interface eth3
set firewall group interface-group LAN interface eth1
set firewall group interface-group Mgmt interface eth0
set firewall group port-group PORT-TEAMS-UDP port '3478-3481'
set firewall group port-group Web-TCP port '80'
set firewall group port-group Web-TCP port '443'
set firewall group port-group Service_TCP-UDP port '53'
set firewall group port-group Service_TCP-UDP port '7777'
set firewall group port-group Service_TCP-UDP port '67'
set firewall group port-group Service_TCP-UDP port '68'

# Rules
set firewall ipv4 name CONN_FILTER default-action 'return'
set firewall ipv4 name CONN_FILTER rule 10 action 'accept'
set firewall ipv4 name CONN_FILTER rule 10 state established
set firewall ipv4 name CONN_FILTER rule 10 state related

set firewall ipv4 name WAN-IN default-action 'drop'

set firewall ipv4 name VyOS_Mgmt default-action 'return'
set firewall ipv4 name VyOS_Mgmt rule 10 action 'accept'
set firewall ipv4 name VyOS_Mgmt rule 10 state new
set firewall ipv4 name VyOS_Mgmt rule 10 state established
set firewall ipv4 name VyOS_Mgmt rule 10 inbound-interface group 'Mgmt'
set firewall ipv4 name VyOS_Mgmt rule 20 action 'accept'
set firewall ipv4 name VyOS_Mgmt rule 20 state related
set firewall ipv4 name VyOS_Mgmt rule 20 inbound-interface group 'Mgmt'


# Chains
## Forward
set firewall ipv4 forward filter rule 10 action 'jump'
set firewall ipv4 forward filter rule 10 jump-target CONN_FILTER

set firewall ipv4 forward filter rule 100 action jump
set firewall ipv4 forward filter rule 100 jump-target WAN-IN
set firewall ipv4 forward filter rule 100 inbound-interface group WAN
set firewall ipv4 forward filter rule 100 destination group network-group HomeLAN-v4

## Input
### Allow internet access.
set firewall ipv4 input filter default-action 'drop'
set firewall ipv4 input filter rule 10 action 'jump'
set firewall ipv4 input filter rule 10 jump-target CONN_FILTER

### Allow Management access. 
set firewall ipv4 input filter rule 20 action jump
set firewall ipv4 input filter rule 20 jump-target VyOS_Mgmt
set firewall ipv4 input filter rule 20 destination group port-group Service_TCP-UDP
set firewall ipv4 input filter rule 20 protocol tcp

### Allow services access
set firewall ipv4 input filter rule 30 action 'accept'
set firewall ipv4 input filter rule 30 icmp type-name 'echo-request'
set firewall ipv4 input filter rule 30 protocol 'icmp'
set firewall ipv4 input filter rule 30 state new
set firewall ipv4 input filter rule 30 inbound-interface group '!WAN'

set firewall ipv4 input filter rule 40 action 'accept'
set firewall ipv4 input filter rule 40 destination group port-group Service_TCP-UDP
set firewall ipv4 input filter rule 40 protocol 'tcp_udp'
set firewall ipv4 input filter rule 40 source group network-group HomeLAN-v4

### Allowing all connections coming from localhost
set firewall ipv4 input filter rule 50 action 'accept'
set firewall ipv4 input filter rule 50 source address 127.0.0.0/8
``` 

</p>
</details>

**Comment by ibehren1** [comment]
@MaurUppi

With regard to 
>but found that I can't delete preseted ssh_group or other config of your example config. Only able to add something.

This was a bug... I have published [v1.4.5](https://github.com/ibehren1/fw-gui/pull/46) that addresses this.  Thanks for bringing it up!

Regarding fine-tuning the firewall configuration, I think I will stay away from giving advice on the specific rules or the level of granularity and effectiveness.

I will tag you when I am able to add Flowtables and will leave the issue open until then.

Thanks for using the tool and please do provide feedback as you have it but please do keep individual issues to a single topic.

**Comment by ibehren1** [comment]
@MaurUppi

You should be able to `docker pull ibehren1/fw-gui:dev-v1.4.6` and add that image to your docker_compose.yml to run a dev version.  In this dev version, you should be able to create flowtables and add filter rules that offload to the flowtables.

I will warn you, I have not tested these options thoroughly but would love your feedback on them.

**Comment by MaurUppi** [comment]
Hi ibehren1

Recently, I’m learning and fine turning the firewall settings. Thus, I’m
thinking, is a possibility that if your tool have a feature to simulate the
rule/ a test running etc. before deploying to the device.
Of course, it has to deploy and confirm if works on system.
What do you think? Daydreaming or doable but hard?

ZHIYONG

**Comment by ibehren1** [comment]
Zhiyong --

It is a lot to try and learn quickly.  I can't see a way to ever test synthetic traffic within the tool, honestly I am not sure even enterprise tools like Palo Alto's Panorama can do that.

What I would suggest is something that this tool does now allow, is to create snapshot of the configuration make a change, commit and test.  If things do not work as planned, roll back to the snapshot and make another change.

Wish you the best and appreciate the support!
Isaac

**Comment by ibehren1** [comment]
Closing issue as Flowtables feature has been available for 1 week.

Please reach out if issues are encountered.
